### PR TITLE
Update socials.xml

### PR DESCRIPTION
**Pull request by spabolu**
changed the overview and description for first-time users to setup it up easily.

### CODE REVIEW

**Comment by diamkil** [comment]
Could you switch it back to 7574 since 3000 is a very common port? Merging one that is switched

**Comment by diamkil** [comment]
Just need to correct it in the WebUI block too and then it's perfect

**Comment by diamkil** [comment]
It should be on CA in a few hours

**Comment by spabolu** [comment]
thank you very much!

**Pull request merged**
